### ISSUE TITLE
Trademark schema uses `InfringingUrl`, which is already covered by `SourceUrl`

### ISSUE THREAD

**Issue by Qdulf** [abusix/xarf#11]
The [Trademark schema](https://github.com/abusix/xarf/blob/master/schemas/trademark.schema.json) has a field called `InfringingUrl`, to specify a url to the trademark infringing content. 

This logic is already covered by `SourceUrl` in [`IpAndUrlBasedReport`](https://github.com/abusix/xarf/blob/master/schemas/xarf_shared.schema.json)

### Proposal
Remove `InfringingUrl`

**Comment by FrederikP** [comment]
This applies not only to trademark, but also copyright. So if we remove it, I guess we should remove it in both.

**Comment by FrederikP** [comment]
https://github.com/abusix/xarf/pull/14 includes this
