### ISSUE TITLE
Your reports have a report per incident, you'd need   "Reports"

### ISSUE THREAD

**Issue by PeterPann23** [abusix/xarf#23]
You should have reports and not report per detection else one can generate GB on extra header data where no one needs this

**Comment by FrederikP** [comment]
At some point it was decided that we wouldn't include a batch report mechanism for now. Often times the amount of overhead relative to the actual report payload is <10%, but of course it can add up in the end. This is only considering the actual xarf overhead, not any overhead by the transporting mechanism (we are already actively working with XARF APIs where the overhead isn't as bad as it might be with email)

I think the decision was made for the following reasons:
- xarf reports should be sent as soon as the abuse was detected, allowing the recipient to act on it quickly
- gathering tons of reports and then sending a daily batch will delay a lot of reports and could lead to a delayed action against the source of the abuse

Can you describe your use case that will lead to so many abuse reports that you are worried about GBs of overhead? It would be interesting to discuss this.

@tknecht any additional thoughts from your side?
