### ISSUE TITLE
Source is this remote? your documentation is missing details

### ISSUE THREAD

**Issue by PeterPann23** [abusix/xarf#24]
Can you clarify?

Your documentation states Source and Destination, who is the source here the sender? I am the destination?

**Comment by FrederikP** [comment]
Hi,

https://github.com/abusix/xarf/blob/49e67ab15a7e2581551f3292a7ea00d1835d5829/schemas/2/xarf_shared.schema.json#L225

there are description fields in the schema. In that case it might not be the best english.

Yes the source in the side that actually abuses. The destination is the target/victim of the abuse.
